"""Mock extraction fixtures used when no extraction LLM is configured."""

MOCK_EVENTS = {
    "finnhub_direct_001": {
        "eventType": "supply_chain",
        "eventSummary": "Apple unveils M5 chip utilizing TSMC 2nm technology.",
        "hardFacts": ["Apple announced M5 chip family", "Uses TSMC 2nm lithography", "40% faster local LLM processing"],
        "entities": ["Apple", "AAPL", "TSMC"],
        "eventTags": ["M5", "semiconductor", "2nm"],
        "regions": ["Taiwan"],
        "sectors": ["technology"],
        "commodities": ["microchips"],
        "technologyThemes": ["semiconductors"],
        "possibleDirectionalPressure": "positive",
        "uncertaintyNotes": ["yield rates of 2nm nodes"],
        "evidence": ["announced its M5 chip family", "leverages TSMC's 2nm lithography"]
    },
    "finnhub_direct_002": {
        "eventType": "earnings",
        "eventSummary": "Microsoft exceeds guidance fueled by 28% cloud growth from Copilot.",
        "hardFacts": ["Cloud revenue expanded 28%", "Boosted by Microsoft 365 Copilot adoption"],
        "entities": ["Microsoft", "MSFT"],
        "eventTags": ["cloud", "Copilot", "earnings"],
        "regions": [],
        "sectors": ["technology"],
        "commodities": [],
        "technologyThemes": ["frontier AI"],
        "possibleDirectionalPressure": "positive",
        "uncertaintyNotes": ["sustainability of Copilot subscription growth"],
        "evidence": ["cloud services grew 28%", "boosted by corporate adoption of Microsoft 365 Copilot"]
    },
    "currents_nvidia_reflection_ai": {
        "eventType": "private_company_technology",
        "eventSummary": "TechRepublic reports Nvidia-backed Reflection AI plans a multibillion-dollar AI data center in South Korea.",
        "hardFacts": ["TechRepublic reports Reflection AI is Nvidia-backed", "Reflection AI plans a multibillion-dollar AI data center in South Korea"],
        "entities": ["Nvidia", "Reflection AI"],
        "eventTags": ["AI infrastructure", "data center", "open AI infrastructure"],
        "regions": ["South Korea"],
        "sectors": ["technology", "AI"],
        "commodities": [],
        "technologyThemes": ["AI infrastructure", "frontier AI"],
        "possibleDirectionalPressure": "positive",
        "uncertaintyNotes": ["Reflection AI is private; the article does not quantify Nvidia's direct financial exposure"],
        "evidence": ["Nvidia-backed Reflection AI plans a multibillion-dollar data center in South Korea"]
    },
    "finnhub_dup_001": {
        "eventType": "supply_chain",
        "eventSummary": "Fire reported at electronics manufacturing zone in Zhengzhou.",
        "hardFacts": ["fire in component warehouse", "Zhengzhou assembly zone", "no casualties"],
        "entities": ["Foxconn", "AAPL"],
        "eventTags": ["Zhengzhou", "fire", "factory"],
        "regions": ["China"],
        "sectors": ["technology"],
        "commodities": [],
        "technologyThemes": [],
        "possibleDirectionalPressure": "negative",
        "uncertaintyNotes": ["damage scale to inventory"],
        "evidence": ["Zhengzhou assembly zone", "fire broke out in a component warehouse"]
    },
    "finnhub_dup_002": {
        "eventType": "supply_chain",
        "eventSummary": "Fire reported at electronics manufacturing zone in Zhengzhou.",
        "hardFacts": ["fire in component warehouse", "Zhengzhou assembly zone"],
        "entities": ["Foxconn", "AAPL"],
        "eventTags": ["Zhengzhou", "fire", "factory"],
        "regions": ["China"],
        "sectors": ["technology"],
        "commodities": [],
        "technologyThemes": [],
        "possibleDirectionalPressure": "negative",
        "uncertaintyNotes": ["production impact"],
        "evidence": ["fire in a Zhengzhou electronics manufacturing plant", "examining potential damage"]
    },
    "finnhub_dup_003": {
        "eventType": "supply_chain",
        "eventSummary": "Fire reported at electronics manufacturing zone in Zhengzhou halts lines.",
        "hardFacts": ["fire in component warehouse", "Zhengzhou assembly zone", "assembly lines halted", "2 million iPhones delayed"],
        "entities": ["Foxconn", "AAPL", "Apple"],
        "eventTags": ["Zhengzhou", "fire", "halt", "iPhone"],
        "regions": ["China"],
        "sectors": ["technology"],
        "commodities": [],
        "technologyThemes": [],
        "possibleDirectionalPressure": "negative",
        "uncertaintyNotes": ["duration of shutdown"],
        "evidence": ["fire in Zhengzhou factory warehouse", "complete shutdown of advanced assembly lines", "delay shipment of 2 million iPhone units"]
    },
    "currents_cross_001": {
        "eventType": "natural_disaster",
        "eventSummary": "7.2 magnitude earthquake in Taiwan prompts foundry evacuations.",
        "hardFacts": ["7.2 magnitude earthquake struck eastern Taiwan", "Semiconductor fabs in Hsinchu evacuated", "Possible calibration damage to lithography tools"],
        "entities": ["Taiwan", "TSMC"],
        "eventTags": ["Taiwan", "earthquake", "lithography", "semiconductor"],
        "regions": ["Taiwan"],
        "sectors": ["technology"],
        "commodities": ["silicon", "microchips"],
        "technologyThemes": ["semiconductors"],
        "possibleDirectionalPressure": "negative",
        "uncertaintyNotes": ["calibration recovery time"],
        "evidence": ["7.2 magnitude earthquake shook eastern Taiwan", "evacuated staff", "calibration damage to high-end lithography equipment"]
    },
    "currents_cross_002": {
        "eventType": "private_company_technology",
        "eventSummary": "Anthropic launches Claude 3.7 Sonnet setting coding benchmarks.",
        "hardFacts": ["Anthropic launched Claude 3.7 Sonnet", "Outperforms platforms in coding, math, chemistry"],
        "entities": ["Anthropic", "Claude"],
        "eventTags": ["Anthropic", "Claude", "model release"],
        "regions": [],
        "sectors": ["technology"],
        "commodities": [],
        "technologyThemes": ["frontier AI"],
        "possibleDirectionalPressure": "positive",
        "uncertaintyNotes": ["pricing structures", "competitor response timeline"],
        "evidence": ["launched Claude 3.7 Sonnet", "achieves state-of-the-art results"]
    },
    "currents_cross_003": {
        "eventType": "geopolitical",
        "eventSummary": "Drone strikes near Bab el-Mandeb reroute Red Sea shipping.",
        "hardFacts": ["Cargo ships targeted by drone strikes in Bab el-Mandeb", "Red Sea route suspended", "Container rates surge 30%"],
        "entities": ["Red Sea", "Bab el-Mandeb"],
        "eventTags": ["Red Sea", "drone strikes", "shipping", "freight rates"],
        "regions": ["Red Sea", "Middle East"],
        "sectors": ["shipping", "airlines"],
        "commodities": ["oil"],
        "technologyThemes": [],
        "possibleDirectionalPressure": "negative",
        "uncertaintyNotes": ["duration of rerouting", "naval security intervention"],
        "evidence": ["targeted by drone strikes near the Bab el-Mandeb", "suspension of Red Sea", "rates surged 30%"]
    }
}

